[package]
name = "apsp_mt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rayon = "1.0"
clap = { version = "3.1.15", features = ["derive"] }
